//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Products = new HashSet<Product>();
        }


        public Category(int categoryId, string categoryName, string description)
        {
            CategoryID = categoryId;
            CategoryName = categoryName;
            Description = description;
        }

        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }

        public override string ToString()
        {
            return "Category\n      ID: " + CategoryID +
                "\n      Name: " + CategoryName +
                "\n      Description: " + Description;
        }
    }
}
