//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Order_Details = new HashSet<Order_Detail>();
        }

        public Product(int productId, string productName, int? categoryId, string quantityPerUnit, decimal? unitPrice, short? unitsInStock, short? unitsOnOrder, short? reorderLevel, bool discontinued, Category category)
        {
            ProductID = productId;
            ProductName = productName;
            CategoryID = categoryId;
            QuantityPerUnit = quantityPerUnit;
            UnitPrice = unitPrice;
            UnitsInStock = unitsInStock;
            UnitsOnOrder = unitsOnOrder;
            ReorderLevel = reorderLevel;
            Discontinued = discontinued;
            Category = category;
        }


        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string QuantityPerUnit { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<short> UnitsInStock { get; set; }
        public Nullable<short> UnitsOnOrder { get; set; }
        public Nullable<short> ReorderLevel { get; set; }
        public bool Discontinued { get; set; }
    
        public Category Category { get; set; }
        public virtual ICollection<Order_Detail> Order_Details { get; set; }
        public virtual Supplier Supplier { get; set; }


        public override string ToString()
        {
            return "Product" + "\n   ID: " + ProductID +
                    "\n   Name: " + ProductName +
                    "\n   " + Category +
                    "\n   QuantityPerUnit: " + QuantityPerUnit +
                    "\n   UnitPrice: " + UnitPrice +
                    "\n   UnitsInStock: " + UnitsInStock +
                    "\n   UnitsOnOrder: " + UnitsOnOrder +
                    "\n   ReorderLevel: " + ReorderLevel +
                    "\n   Discontinued: " + Discontinued;
        }
    }
}
